env:
  browser: true
  es2021: true
extends:
  - standard-with-typescript
  - prettier
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project:
    - "tsconfig.json"
rules:
  no-return-await: off
  "@typescript-eslint/return-await":
    - error
    - in-try-catch
